In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)

In [4]:
x_ones = torch.ones_like(x_np)
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand_int = torch.rand_like(x_rand, dtype = torch.float)
print(f"{x_ones}\n{x_rand}\n{x_rand_int}")

tensor([[1, 1],
        [1, 1]])
tensor([[0.8021, 0.5869],
        [0.1773, 0.2893]])
tensor([[0.4297, 0.9245],
        [0.9842, 0.3842]])


In [5]:
shape = (2,9,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("{}\n{}\n{}".format(rand_tensor, ones_tensor, zeros_tensor))

tensor([[0.0825, 0.0437, 0.6451, 0.0476, 0.2180, 0.3951, 0.1249, 0.0196, 0.8407],
        [0.4619, 0.1924, 0.1582, 0.5483, 0.0790, 0.4561, 0.7017, 0.4704, 0.8453]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [6]:
print("{} {} {}".format(rand_tensor.shape, rand_tensor.dtype, rand_tensor.device))

torch.Size([2, 9]) torch.float32 cpu


In [7]:
tensor = torch.ones(4,4)
print(tensor)
print(f"row1 : {tensor[0]}")
print(f"col1 : {tensor[:, 0]}")

tensor[:, -1] = 0

print(f"""
      col_last : {tensor[:, -1]}
      col_last_alt : {tensor[..., -1]}
      
      notice : tensor[..., -1] = tensor[:,:,:,~~~생략~~~,-1]
""")
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
row1 : tensor([1., 1., 1., 1.])
col1 : tensor([1., 1., 1., 1.])

      col_last : tensor([0., 0., 0., 0.])
      col_last_alt : tensor([0., 0., 0., 0.])
      
      notice : tensor[..., -1] = tensor[:,:,:,~~~생략~~~,-1]

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
