In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)

In [4]:
x_ones = torch.ones_like(x_np)
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand_int = torch.rand_like(x_rand, dtype = torch.float)
print(f"{x_ones}\n{x_rand}\n{x_rand_int}")

tensor([[1, 1],
        [1, 1]])
tensor([[0.7406, 0.0448],
        [0.7204, 0.9688]])
tensor([[0.0235, 0.3344],
        [0.9608, 0.2255]])


In [5]:
shape = (2,9,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("{}\n{}\n{}".format(rand_tensor, ones_tensor, zeros_tensor))

tensor([[0.7170, 0.5234, 0.3596, 0.5215, 0.6833, 0.1425, 0.8823, 0.7975, 0.6676],
        [0.3546, 0.2452, 0.8809, 0.0808, 0.1342, 0.8248, 0.1668, 0.3465, 0.6358]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [6]:
print("{} {} {}".format(rand_tensor.shape, rand_tensor.dtype, rand_tensor.device))

torch.Size([2, 9]) torch.float32 cpu


In [7]:
tensor = torch.ones(2,4)
print(tensor)
print(f"row1 : {tensor[0]}")
print(f"col1 : {tensor[:, 0]}")

tensor[:, -1] = 0

print(f"""
      col_last : {tensor[:, -1]}
      col_last_alt : {tensor[..., -1]}
      
      notice : tensor[..., -1] = tensor[:,:,:,~~~생략~~~,-1]
""")
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
row1 : tensor([1., 1., 1., 1.])
col1 : tensor([1., 1.])

      col_last : tensor([0., 0.])
      col_last_alt : tensor([0., 0.])
      
      notice : tensor[..., -1] = tensor[:,:,:,~~~생략~~~,-1]

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1_x= torch.cat([tensor, tensor, tensor], dim = 0)
print(f"\n{t1} \n\n {t1_x} \n")

t2 = torch.stack([tensor, tensor, tensor], dim = 2)
# t2 = torch.stack([tensor, tensor, tensor], dim = 1 #or 0) << 차이가 없음 
print(t2)

print(f"\n{t2[:,:,-1]} \n\n {t2[..., -1]}") #***


tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]]) 

 tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]]])

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 

 tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [9]:
t1 = torch.tensor([[1,2,3]])

print(t1.shape)

y1 = t1 @ t1.T
y2 = t1.matmul(t1.T)

print(y1==y2)

z1 = t1 *t1
z2 = t1.mul(t1)

z3 = torch.rand((1,3,))

torch.mul(t1,t1,out=z3) #

print(torch.equal(z1, z2) and torch.equal(z2,z3))
print(f"\n{z3}")

torch.Size([1, 3])
tensor([[True]])
True

tensor([[1., 4., 9.]])


In [10]:
agg = z3.sum()
agg_item = agg.item() #기본 float 자료형으로 변형
print(agg_item, type(agg_item)) #tensor-dtype, python-type

14.0 <class 'float'>


In [11]:
#-----권장되지는 않는.. "바꿔치기 연산"-----

print(f"{z3}\n")

z3.add(5) #z3에는 변화가 없다
print(z3)

print('\n')

z3.add_(5) # << 바꿔치기 연산
print(z3)

# 계속 실행하면 값이 계속 바뀜
# 바꿔치기 되었으므로..

tensor([[1., 4., 9.]])

tensor([[1., 4., 9.]])


tensor([[ 6.,  9., 14.]])


In [12]:
z3 = z2 #초기화 하고 위에 블록 다시 실행해보셈

이렇게 바꿔치기 연산은 메모리를 아끼지만 디버깅이 어렵고 과거 기록을 지워버리기 때문에 잘 안쓴다는~

In [13]:
t = torch.ones(5)
print(f"t : {t}")

n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [14]:
#텐서와 넘파이 배열은 동일한 메모리를 점거
t.add_(1)
print(f"{t}\n{n}")

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n) #
print(f"{n}\n{t}")

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## t->n 변환과 n->t 변환 방식이 다르다 / 그 이유

### 1. torch -> numpy : n = t.numpy()
> 인스턴스 매서드

tensor는 이미 메모리 내 구조화된 객체. 해당 tensor에서 더 낮은 차원로 잘랜서 간단히 넘기면 그게 numpy

### 2. numpy -> torch : t = torch.from_numpy(n) 
> 스태틱 함수 (라이브러리에 포함된)

tensor는 numpy의 상위 개념. 따라서 numpy 써서 tensor를 만들어줄 토치의 스태틱 함수가 있어야..

단, 둘 다 메모리를 공유한다 & n과 t는 같은 메모리 내용을 참조한다 .

(끝에 clone() 붙이면 분리 가능)