<a href="https://colab.research.google.com/github/howonJeong/Journey_to_TinyLLAMA/blob/main/Step1_MitDeep/1_6_1_SimpleNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
import shutil

source_path = '/content/drive/MyDrive/common' # 구글 드라이브 내 'common' 폴더 경로
destination_path = '/content/common'         # Colab 환경의 대상 경로

if not os.path.exists(source_path):
    print(f"Warning: Source path '{source_path}' does not exist. Please ensure 'common' folder is in your Google Drive.")
elif os.path.exists(destination_path):
    print(f"'{destination_path}' already exists. Skipping copy.")
else:
    try:
        shutil.copytree(source_path, destination_path)
        print(f"Successfully copied '{source_path}' to '{destination_path}'.")
    except Exception as e:
        print(f"Error copying folder: {e}")

# 'common' 폴더가 /content 에 복사되었는지 확인
if os.path.exists('/content/common'):
    print("'/content/common' exists. You can now try re-running the import cell (Rplqrn_UrwNx).")
else:
    print("'/content/common' does not exist. Please check your Google Drive path and try again.")

'/content/common' already exists. Skipping copy.
'/content/common' exists. You can now try re-running the import cell (Rplqrn_UrwNx).


In [ ]:
import sys, os
sys.path.append(os.path.join(os.getcwd(), '..'))
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [ ]:
class simpleNet:
  def __init__(self):
    self.W = np.random.randn(4,4)
    #정규분포 랜덤 가중치로 스타토

  def predict(self, x):
    return np.dot(x, self.W)

  def loss(self, x, t):
    z = self.predict(x)
    y = softmax(z)
    loss = cross_entropy_error(y, t)

    return loss

In [ ]:
net = simpleNet()
print(net.W)

[[ 1.79092386  0.91100096  1.43099078 -1.18863763]
 [ 0.03979179  0.14933067 -0.03396979  0.59407467]
 [ 0.2311054  -0.28981915 -0.27596246 -0.48389472]
 [ 1.21824741 -0.05578332  1.05593996 -0.86789463]]


In [ ]:
x = np.array([0.6, 0.9, 0.1, 0.1])
p = net.predict(x) #앞에 넷
print(p)

[ 1.25530221  0.64643793  0.90601941 -0.31369431]


In [ ]:
np.argmax(p)
#최댓값의 인덱스

np.int64(0)

In [ ]:
t = np.array([0,0,1,0]) #정답 레이블 / 인덱스
net.loss(x, t)

np.float64(1.2483928580576462)

In [ ]:
def f(W):
  return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.24415882  0.13281466 -0.42782054  0.05084706]
 [ 0.36623822  0.19922199 -0.64173081  0.0762706 ]
 [ 0.04069314  0.02213578 -0.07130342  0.00847451]
 [ 0.04069314  0.02213578 -0.07130342  0.00847451]]


In [ ]:
f = lambda w: net.loss(x,t)

In [ ]:
print(numerical_gradient(f, net.W))
#람다 써도 되고..

[[ 0.24415882  0.13281466 -0.42782054  0.05084706]
 [ 0.36623822  0.19922199 -0.64173081  0.0762706 ]
 [ 0.04069314  0.02213578 -0.07130342  0.00847451]
 [ 0.04069314  0.02213578 -0.07130342  0.00847451]]
